site_name: Crate Validation Service
nav:
  - Home: index.md
  - Installation: installation.md
  - API: api.md
  - ENTRUST: entrust.md
  - Contributions: contribution.md
theme: readthedocs
plugins:
  - search
  - mermaid2
  - likec4
markdown_extensions:
  - admonition
