site_name: RO-Crate Validation Service
nav:
  - Home: index.md
  - Installation: installation.md
  - Upgrading: upgrading.md
  - API: api.md
  - Five Safes RO-Crate: five-safes.md
  - Contributions: contribution.md
theme: readthedocs
plugins:
  - search
  - mermaid2
markdown_extensions:
  - admonition
