site_name: Crate Validation Service
plugins:
  - search
  - likec4
nav:
  - Home: index.md
  - Installation: installation.md
  - API: api.md
  - ENTRUST: entrust.md
  - Contributions: contribution.md
theme: readthedocs
